name: 'Discord Webhook'
description: 'A GitHub action to call a Discord Webhook'
author: 'Braydon Hall'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true

  discord-webhook:
    description: 'The WebHook URL to call. Should be stored in Secrets on the Repository'
    required: true

  username:
    description: 'Overrides the current username of the webhook'
    required: false
    default: 'GitHub Actions'

  avatar-url:
    description: 'Overrides the current avatar of the webhook'
    required: false
    default: 'https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg'

  title:
    description: 'Overrides the default title. Include the status in the title by adding the {{STATUS}} placeholder.'
    required: false
  
  description:
    description: 'The message to display. Include the status in the description by adding the {{STATUS}} placeholder'
    required: false
  
  include-details:
    description: 'Whether or not to include the job breakdown of the Workflow run'
    required: false
    default: 'true'
  
  color-success:
    description: 'Overrides the default success color'
    required: false
    default: '17cf48'
  
  color-failure:
    description: 'Overrides the default failure color'
    required: false
    default: 'e72727'

  color-cancelled:
    description: 'Overrides the default cancelled color'
    required: false
    default: 'd3d3d3'

runs:
  using: 'node12'
  main: 'dist/index.js'