name: 'Discord Workflow Status Notifier'
description: 'A GitHub action to report workflow and job status to a Discord Webhook'
author: 'José Duarte'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true

  discord-webhook:
    description: 'The WebHook URL to call. Should be stored in Secrets on the Repository'
    required: true

  username:
    description: 'Overrides the current username of the webhook'
    required: false
    default: 'GitHub Actions'

  avatar-url:
    description: 'Overrides the current avatar of the webhook'
    required: false
    default: 'https://avatars0.githubusercontent.com/u/44036562?s=200&v=4'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'message-square'
  color: 'gray-dark'
